# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n insar
# enter  environment : conda activate insar
# exit   environment : conda deactivate
name: insar
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.6
    - cartopy
    - cdsapi
    - cvxopt
    - dask>=1.0
    - dask-jobqueue>=0.3
    - ecCodes
    - gdal>=3.0
    - h5py
    - hdf5
    - isce2
    - joblib
    - jupyterlab
    - jupyter_contrib_nbextensions
    - libgdal
    - lxml
    - matplotlib
    - nbdime
    - netcdf4
    - numpy
    - openmp
    - pandas
    - pip
    - pygrib
    - pyhdf
    - pykdtree
    - pyproj
    - pyresample
    - requests
    - rise
    - shapely
    - scikit-image
    - scikit-learn
    - scipy
    - pip:
        - git+https://github.com/tylere/pykml.git
